### ISSUE TITLE
How to add more Database fields

### ISSUE THREAD

**Issue by bkrajendra** [vojtasvoboda/oc-userimportexport-plugin#3]
How to add more Database fields to import

**Comment by vojtasvoboda** [comment]
It is not variable for now. If you want to do that quickly, just update https://github.com/vojtasvoboda/oc-userimportexport-plugin/blob/master/models/userimport/columns.yaml file.

**Comment by bkrajendra** [comment]
@vojtasvoboda 
I tried this already but somehow its not updating in database. do I need any code to be added in model
this is what ive done:
```yaml
# ===================================
#  Column Definitions
# ===================================

columns:

    username:
        label: rainlab.user::lang.user.username
        searchable: true
        invisible: true

    name:
        label: rainlab.user::lang.user.name
        searchable: true

    surname:
        label: rainlab.user::lang.user.surname
        searchable: true
        invisible: true

    email:
        label: rainlab.user::lang.user.email
        searchable: true

    mobilef:
          label: Fathers Mobile 
          searchable: true

    mobilem:
          label: Mothers Mobile 
          searchable: true

    rollno:
          label: Roll No 
          searchable: true

    # street_addr:
    #     label: Street
    #     searchable: true

    # city:
    #     label: City

    # zip:
    #     label: ZIP
```
Ive these mobilef, mobilem and rollno columns in db already.
